name: pl_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_2
  - altair=5.5.0=py311haa95532_0
  - aom=3.12.1=h00a0c3c_0
  - arrow-cpp=21.0.0=h6358905_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - attrs=25.4.0=py311haa95532_2
  - aws-c-auth=0.9.0=h02ab6af_2
  - aws-c-cal=0.9.2=h02ab6af_1
  - aws-c-common=0.12.4=h02ab6af_0
  - aws-c-compression=0.3.1=h02ab6af_2
  - aws-c-event-stream=0.5.6=h02ab6af_0
  - aws-c-http=0.10.4=h02ab6af_0
  - aws-c-io=0.21.4=h02ab6af_0
  - aws-c-mqtt=0.13.3=h02ab6af_0
  - aws-c-s3=0.8.7=h02ab6af_0
  - aws-c-sdkutils=0.2.4=h02ab6af_1
  - aws-checksums=0.2.7=h02ab6af_1
  - aws-crt-cpp=0.34.0=h885b0b7_0
  - aws-sdk-cpp=1.11.638=hf0af688_0
  - beautifulsoup4=4.14.2=py311haa95532_0
  - blas=1.0=mkl
  - blinker=1.9.0=py311haa95532_1
  - bottleneck=1.4.2=py311h540bb41_1
  - brotlicffi=1.1.0.0=py311h885b0b7_0
  - bs4=4.14.2=py311hd3eb1b0_0
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.12.2=haa95532_0
  - cachetools=5.5.1=py311haa95532_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2025.11.12=py311haa95532_0
  - cffi=2.0.0=py311h02ab6af_1
  - charset-normalizer=3.4.4=py311haa95532_0
  - click=8.2.1=py311haa95532_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311h214f63a_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.8.17=py311h5dfdfe8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h9214b88_0
  - filelock=3.20.0=py311haa95532_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.60.1=py311h02ab6af_0
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - fsspec=2025.10.0=py311h4442805_0
  - gflags=2.2.2=hd77b12b_1
  - gitdb=4.0.12=py311haa95532_0
  - gitpython=3.1.45=py311haa95532_0
  - glog=0.5.0=hd77b12b_1
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py311h827c3e9_0
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=10.2.0=he2f9f60_1
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.11=py311haa95532_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.7.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py311haa95532_0
  - joblib=1.5.2=py311haa95532_0
  - jpeg=9f=ha349fce_0
  - jsonschema=4.25.0=py311haa95532_1
  - jsonschema-specifications=2025.9.1=py311haa95532_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - kiwisolver=1.4.9=py311h03f52e7_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=h3732fa5_0
  - lerc=4.0.0=h5da7b33_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libavif=1.3.0=h5bd13ec_0
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libclang13=20.1.8=default_hccbf073_0
  - libcurl=8.16.0=h97e0424_0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.4=hfaec014_0
  - libgrpc=1.71.0=hf4237ab_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - libllvm20=20.1.8=h3aa9ab2_0
  - libmpdec=4.0.0=h827c3e9_0
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.50=h46444df_0
  - libpq=17.6=h652a1e2_0
  - libprotobuf=5.29.3=h65a231f_1
  - libre2-11=2024.07.02=h5da7b33_0
  - libsodium=1.0.20=hc70643c_0
  - libssh2=1.11.1=h2addb87_0
  - libthrift=0.22.0=ha2884a9_0
  - libtiff=4.7.1=h3a18249_0
  - libtorch=2.7.0=cpu_mkl_h017a133_100
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libxgboost=3.0.1=h585ebfc_0
  - libxml2=2.13.9=h6201b9f_0
  - libxslt=1.1.43=hd1fac9c_0
  - libzlib=1.3.1=h02ab6af_0
  - lxml=5.3.0=py311h985e36a_2
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py311h827c3e9_0
  - matplotlib=3.10.6=py311haa95532_1
  - matplotlib-base=3.10.6=py311h43afe63_1
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py311h0b37514_0
  - mkl_fft=2.1.1=py311h300f80d_0
  - mkl_random=1.3.0=py311ha5e6156_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py311haa95532_0
  - mysql-common=9.3.0=hf582a5b_3
  - mysql-libs=9.3.0=hc0ebf12_3
  - narwhals=2.7.0=py311haa95532_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=py311haa95532_0
  - numexpr=2.14.1=py311h7660c64_0
  - numpy=2.3.5=py311h050da96_0
  - numpy-base=2.3.5=py311h1e017a8_0
  - openssl=3.6.0=h725018a_0
  - opentelemetry-api=1.38.0=py311haa95532_0
  - orc=2.2.0=hf43e1a1_0
  - packaging=25.0=py311haa95532_1
  - pandas=2.3.3=py311h42c1672_1
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.1=py311haa95532_0
  - pcre2=10.46=h5740b90_0
  - pillow=12.0.0=py311h4212202_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - protobuf=5.29.3=py311h5da7b33_0
  - psutil=7.1.3=py311hf893f09_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-xgboost=3.0.1=py311haa95532_0
  - pyarrow=21.0.0=py311ha5e6156_0
  - pycparser=2.23=py311haa95532_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=py311haa95532_0
  - pyqt=5.15.11=py311h816affc_0
  - pyqt5-sip=12.17.0=py311h02ab6af_0
  - pysocks=1.7.1=py311haa95532_1
  - python=3.11.5=he1021f5_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytorch=2.7.0=cpu_mkl_py311he241c65_100
  - pytz=2025.2=py311haa95532_0
  - pywin32=311=py311hefeebc8_1
  - pyyaml=6.0.3=py311hb9a58be_0
  - pyzmq=27.1.0=py311hb77b9c8_0
  - qt-main=5.15.2=h8b2cd8b_13
  - qtbase=6.9.2=hd965823_2
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebsockets=6.9.2=heb02b0b_1
  - re2=2024.07.02=h214f63a_0
  - referencing=0.37.0=py311haa95532_0
  - requests=2.32.5=py311haa95532_1
  - rpds-py=0.28.0=py311h114bc41_0
  - scikit-learn=1.7.2=py311h9296b3f_0
  - scipy=1.16.3=py311hbd6d557_0
  - seaborn=0.13.2=py311haa95532_3
  - setuptools=80.9.0=py311haa95532_0
  - sip=6.12.0=py311h706e071_0
  - six=1.17.0=py311haa95532_0
  - skorch=1.3.0=pyhc455866_0
  - sleef=3.5.1=h8cc25b3_2
  - smmap=5.0.2=py311haa95532_0
  - snappy=1.2.1=hcdb6601_0
  - soupsieve=2.5=py311haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - streamlit=1.51.0=py311haa95532_0
  - sympy=1.14.0=py311haa95532_0
  - tabulate=0.9.0=py311haa95532_0
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - tenacity=9.1.2=py311haa95532_0
  - threadpoolctl=3.5.0=py311h746a85d_0
  - tk=8.6.15=hf199647_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.5.1=py311h827c3e9_0
  - tqdm=4.67.1=py311h4442805_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=py311haa95532_0
  - typing_extensions=4.15.0=py311haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py311haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - watchdog=6.0.0=py311haa95532_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_1
  - xgboost=3.0.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
prefix: C:\Users\tavakola\.conda\envs\pl_env
